/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import login.Login;

/**
 *
 * @author Ranga Hrushikesh.R
 */
class node{
    int [] a=new int[5];
    int size;
    node[] next=new node[4];
    node  parent;
    node(){
        for(int i = 0; i < 4; i++)
	  next[i] = null;
      parent = null;
      size = 0; 
    }
}
public class add extends javax.swing.JFrame {
node root=new node();
    /**
     * Creates new form add
     */
    public add() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("img_name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("category");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("resolution");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 74, -1));

        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 74, -1));

        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("shot_by");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 74, -1));

        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("key");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 74, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 91, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 91, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 91, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 91, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 91, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 91, -1));

        jButton1.setText("insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/fotograaf.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -80, 520, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    node split(node n){
         int midpoint = (n.size+1)/2;
    int newsize = n.size - midpoint;
    node newptr = new node();
    node child;
    newptr.parent = n.parent;
    int i;
    for(i = 0; i < midpoint; i++)
    {
	newptr.a[i] = n.a[i];
	newptr.next[i] = n.next[i];
	n.a[i] = n.a[i+midpoint];
	n.next[i] = n.next[i+midpoint];
    }
    n.size = midpoint;
    newptr.size = newsize;
    for( i = 0; i < n.size; i++)
    {
	child = n.next[i];
	if(child!= null)
	child.parent = n;
    }
    for( i  = 0; i < newptr.size; i++)
    {
	child = newptr.next[i];
	if(child!= null)
	child.parent = newptr;
    }
    return newptr;
    }
    
    void updateKey(node parent,node child,int newKey){
     if( parent == null)
	return;
      if(parent.size == 0)
	    return;
      int oldkey = child.a[child.size-2];
      
      for(int i = 0; i < parent.size;i++)
	  if(parent.a[i] == oldkey)
	  {  parent.a[i] = newKey;
	     parent.next[i] = child;
	  }
    }

    public int search(int key){
        if(root == null)
      {	  System.out.println("The tree Does not exist");
	  return -1;
      }
      int level = 0;
      node leaf = fkey1Leaf(key,level);
      int flag = 0;
      for(int i = 0; i < leaf.size; i++)
	  if(leaf.a[i] == key)
	  {
	      flag = 1;
	      System.out.println("The Key "+key+" Exists in the B-Tree ");//at the level"+level);

	  }
      if(flag!=1)
	  System.out.println("The Key Searched for was not found");
      return flag;
}
    
     public node fkey1Leaf(int key,int level){
         node ptr = root;
         node prevptr = null;
        level = 0;
    int i;
    while(ptr!=null)
    {
	 i = 0;
	  level++;
	 while(i < ptr.size-1 && key > ptr.a[i])
		i++;
	  prevptr = ptr;
	 ptr = ptr.next[i];
    }
    return prevptr;
    }
     
     
public void insert(int key)
	{
		if (root == null)
		{
		  root = new node();
		  root.a[root.size] = key;
		  root.size++;
                  return;
		}
                int level=0;
		node leaf = fkey1Leaf(key,level);
		int i;
		for (i = 0; i < leaf.size; i++)
		{
		if (leaf.a[i] == key)
		{
			System.out.print("The Record to be inserted already exists");
			System.out.print("\n");
			return;
		}
		}
		promote(leaf,key,null);
		 System.out.print("---------------\n");
		 try{  
                     File fle = new File("E:\\traverse.txt");
                     if (fle.createNewFile()){
                     System.out.println("File is created!");
                    }else{
                    System.out.println("File already exists.");
                    }
                    FileWriter fw = new FileWriter(fle,true);
                    fw.write("-----------------\n");
                    fw.close();
                  }
                    catch(Exception e)
                    {
                    }       
                 traverse(root);
		  System.out.print("---------------- \n");
                  try{ 
                      FileWriter fw=new FileWriter("E:\\traverse.txt",true);
                        fw.write("-----------------\n");
                        fw.close();
                    }
                    catch(Exception e)
                    {
                    }       
	}
    
    
    void insertIntoNode(node n,int key,node address){
    int i;
    if( n == null)
	return;
    
    for(i = 0; i < n.size; i++)
	if(n.a[i] == key)
	    return;

    i = n.size-1;
    while(i >= 0 && n.a[i] > key)
    {
	n.a[i+1] = n.a[i];
	n.next[i+1] = n.next[i];
	i--;
    }
    i++;
    n.a[i] = key;
    n.next[i] = address;
    n.size++;
    if( i == n.size-1)
	updateKey(n.parent,n,key);
    }
    
    
     void promote(node n,int key,node address){
    if( n == null)
	return;

    if(n.size < 4)
    {
	insertIntoNode(n,key,address);
	return;
    }

    if( n == root)
    {
	root = new node();
	n.parent = root;
    }
    node newptr = split(n);
    node t;
    if(key < n.a[0])
	  t = newptr;
    else
	  t = n;
    insertIntoNode(t,key,address);
    promote(n.parent,n.a[n.size-1],n);
    promote(newptr.parent,newptr.a[newptr.size-1],newptr);
    
}
void traverse(node ptr){
                if(ptr == null)
                return;
                 for(int i = 0; i < ptr.size; i++)
                {
                    System.out.print(ptr.a[i]+" ");
                  try{  FileWriter fw=new FileWriter("E:\\traverse.txt",true);
                    fw.write(ptr.a[i]+" ");
                    fw.close();
                }
                
                catch(Exception e)
                {
                    System.out.println("Exception");
                }
                }
                try{
                    FileWriter fw=new FileWriter("E:\\traverse.txt",true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    bw.newLine();
                    bw.close();
                   fw.close();
                }
                catch(Exception e)
                {
                }
                System.out.println();
                for(int i = 0; i < ptr.size;i++)
                    traverse(ptr.next[i]);
}
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String str1,str2,str3,str4,str5,str6;
        str1=jTextField1.getText();
        str2=jTextField2.getText();
        str3=jTextField3.getText();
        str4=jTextField4.getText();
        str5=jTextField5.getText();
        str6=jTextField6.getText();
        
        try {
            FileWriter fw=new FileWriter("E://insert.txt",true);
            fw.write(str1);
            fw.write(",");
            fw.write(str2);
            fw.write(",");
            fw.write(str3);
            fw.write(",");
            fw.write(str4);
            fw.write(",");
            fw.write(str5);
            fw.write(",");
            fw.write(str6);
            fw.write(",");
            fw.write("\n");
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(add.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        int istr6;
        istr6=Integer.parseInt(str6);
        Login l=new Login();
        l.insert1(istr6);
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          page2 p2=new page2();
          p2.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
