/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import login.Login;
import static login.Login.insert1;
/**
 *
 * @author Ranga Hrushikesh.R
 */
class records1
{
    public String img_name,category,resolution,address,shot_by,key;
    int key1;
}
public class searchPage extends javax.swing.JFrame {
int n=0;
    /**
     * Creates new form searchPage
     */
    public searchPage() {
        initComponents();
        String buffer;
        try {
            Scanner scan = new Scanner(new File("E://insert.txt"));
            scan.useDelimiter("\n");
            while(scan.hasNext())
            {
                buffer=scan.next();
                n++;
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(653, 459));
        getContentPane().setLayout(null);

        jLabel1.setText("Enter the key to be searched");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 170, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 20, 113, 20);

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 20, 90, 23);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 280, 40);

        jLabel3.setText("Image Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 110, 172, 14);

        jLabel4.setText("Category:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 172, 14);

        jLabel5.setText("Resolution:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 150, 172, 14);

        jLabel6.setText("Address:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 170, 172, 14);

        jLabel7.setText("Shot_by:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 190, 180, 14);

        jLabel8.setText("Key:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 210, 172, 14);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 370, 130, 23);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/ho1.jpeg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-90, 0, 750, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        records1 rec[]=new records1[50];
        for(int i=0;i<50;i++)
        {
            rec[i]=new records1();
        }
         try {
            
            Scanner s=new Scanner(new File("E://insert.txt"));
            s.useDelimiter(",");
            //int k=0;
            for(int i=0;i<n;i++)
            {
                rec[i].img_name=s.next();
                rec[i].category=s.next();
                rec[i].resolution=s.next();
                rec[i].address=s.next();
                rec[i].shot_by=s.next();
                rec[i].key1=s.nextInt();
                rec[i].key=Integer.toString(rec[i].key1);
                //k=rec[i].key;
                //System.out.println("Key: "+k);
                //insert1(k);
                
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        String key=jTextField1.getText();
        int k=Integer.parseInt(key);
        Login l=new Login();
        int flag=l.search1(k);
        //if(flag==1)
         if(flag==1)
        {
            jLabel2.setText("Record with key "+k+" exists");
            for(int i=0;i<n;i++)
             {
                 if(key.equals(rec[i].key))
                 {
                     jLabel3.setText("Image_name: "+rec[i].img_name);
                     jLabel4.setText("category: "+rec[i].category);
                     jLabel5.setText("resolution: "+rec[i].resolution);
                     jLabel6.setText("address: "+rec[i].address);
                     jLabel7.setText("shot_by: "+rec[i].shot_by);
                     jLabel8.setText("key: "+rec[i].key);
                 }
             }
        }   
        else
            jLabel2.setText("Record with key "+k+" does not exists");
        
             
        
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        page2 p2=new page2();
            p2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
